#!/bin/bash

# Update the package index
sudo apt-get update

# Install required dependencies
sudo apt-get install -y wget

# Download the Splunk installation package
wget -O splunk-9.1.1-64e843ea36b1-linux-2.6-amd64.deb "https://download.splunk.com/products/splunk/releases/9.1.1/linux/splunk-9.1.1-64e843ea36b1-linux-2.6-amd64.deb"

# Extract the Splunk package
sudo dpkg -i splunk-9.1.1-64e843ea36b1-linux-2.6-amd64.deb

# Splunk Enterprise is configured to start
sudo /opt/splunk/bin/splunk enable boot-start --accept-license 

# Start Splunk and accept the license agreement
sudo /opt/splunk/bin/splunk start --accept-license --answer-yes

# Prompt the user to set up a username and password for Splunk
sudo /opt/splunk/bin/splunk edit user admin -password YOUR_PASSWORD -role admin -auth admin:changeme

#allow incoming SSH traffic
sudo ufw allow openSSH

#allow incoming network traffic on port 8000 through the UFW (Uncomplicated Firewall) 
sudo ufw allow 8000

#check the current status of your firewall and activate it to apply the defined rules and settings
sudo ufw status
sudo ufw enable

# Set Splunk to start
sudo /opt/splunk/bin/splunk start
